# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

        trigger:
        - main

        pool:
          vmImage: 'ubuntu-latest' # set to windows-latest or another Windows vmImage for Windows builds

        variables:
          imageName: 'home'

        steps:
        - task: Docker@2
          displayName: Login to ACR
          inputs:
            command: login
            containerRegistry: dockerRegistryServiceConnection1
        - task: Docker@2
          displayName: Build an image
          inputs:
            repository: criptoland.azurecr.io/home
            command: buildAndPush
            Dockerfile: Dockerfile
